env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: 
  - files:
      - '**/__tests__/**/*.+(ts|tsx|js)'
      - '**/?(*.)+(spec|test).+(ts|tsx|js)'
    extends:
      - plugin:jest/recommended
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
parserOptions:
  ecmaVersion: latest
  sourceType: module
project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - jest-dom
  - testing-library
rules: {
  react-hooks/rules-of-hooks: error,
  react-hooks/exhaustive-deps: warn
}
